service: node-cloud-demo
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: node-cloud-demo
    distributionFolder: dist/app
    errorDocument: index.html
